project:
  type: book
  output-dir: docs
  resources:
    - assets/

book:
  title: "Single-Cell Omics Tutorials"
  subtitle: "End-to-end workflows for multi-omics analysis in R"
  author: "Sarintip Nguantad"
  date: today
  date-format: "MMMM YYYY"
  doi: ""
  repo-url: https://github.com/tipsarin/scOmics
  repo-actions: [issue]
  sharing: [twitter, linkedin]
  search: true

  sidebar:
    style: floating
    background: none
    logo: assets/VClabLogo.png

  page-footer:
    left: "© Copyright 2025, Sarintip Nguantad"
    right: "Built with [Quarto](https://quarto.org)"

  chapters:
    - index.qmd
    - getting-started.qmd

    - part: "**scRNA-seq**"
      chapters:
        - tutorials/scrna/01-qc-filtering.qmd
        - tutorials/scrna/02-normalization.qmd
        - tutorials/scrna/07-trajectory.qmd
        - tutorials/scrna/r_test.qmd
        - tutorials/scrna/dandelion_test.ipynb

    - part: "**scATAC-seq**"

    - part: "**Spatial Transcriptomics**"

    - part: "**Multi-omics & Genotyping**"
      chapters:
        - tutorials/multiomics/02-signac.qmd

    - references.qmd

format:
  html:
    theme:
      light: sketchy
      dark: sketchy
    back-to-top-navigation: true
    css: assets/custom.css
    code-fold: true
    code-tools: true
    code-copy: true
    code-line-numbers: false
    code-block-bg: true
    smooth-scroll: true
    html-math-method: katex
    toc: true
    toc-depth: 3
    number-sections: false
    number-depth: 3
    highlight-style: github
    fig-align: center
    fig-width: 8
    fig-height: 6
    link-external-newwindow: true


execute:
  freeze: true
  eval: true
  echo: true
  warning: false
  message: false
  cache: true

knitr:
  opts_knit:
    root.dir: "/home/shared/Git/scOmics/sc-omics-book"
  opts_chunk:
    R.options:
      .libPaths: ["/home/sarintip/R/x86_64-pc-linux-gnu-library/4.5.1"]

bibliography: references.bib
csl: nature.csl
