---
title: "Untitled"
subtitle: "Assess and remove low-quality cells before downstream analysis"
author: "Sarintip"
categories: [scRNA-seq, Seurat, QC]
date: "2024-10-06"
format:
  html:
    code-fold: true   # Enables folding for code chunks
    code-tools: true
    toc: true         # Adds a table of contents
    toc-depth: 4    # Set depth to 4 (includes H1 to H4)
---

## Setup

```{r}
#| label: setup
#| eval: true
#| code-fold: false
#| warning: false
library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
options(future.globals.maxSize = 100 * 1000 * 1024^2)
```

**Extend limit to access to certain global variables**

1GB = 1000 \* 1024\^2

[Parallelization in Seurat with future](https://satijalab.org/seurat/archive/v3.0/future_vignette.html)

```{r}
#| eval: false
options(future.globals.maxSize = 100 * 1000 * 1024^2)
```

**Change the current plan to access parallelization**

```{r}
#| eval: false
plan("multicore", workers = 20)
plan()
```

::: callout-Tips
Bypass argument when you running R script via bash script.

`args <- commandArgs(trailingOnly = TRUE)`

`sample_name = args[1]`
:::

```{r}
#| label: argument
#| eval: false
sample_name = "B9rxn1"

scRNA.cellranger_path = paste0("~/All_projects/cellranger_outputs/GRCh38_2024A/v901/", "CVc",
                               sample_name,
                               "_GEX_v901_ref2024A_SC5P-R2_R126-R290_cell23000/outs/filtered_feature_bc_matrix") 


scRNA.cellbender_path = paste0("~/All_projects/analysis_outputs/cellbender/GRCh38_ref2024A/learningrate1e-5/", "CVc",
                               sample_name, "/",
                               "CVc", sample_name, "_cb_v032_FPR_0.05_seurat.h5") 

scRNA.demux_path = paste0("~/All_projects/demuxlet_outputs/GRCh38_ref2024A/demuxlet_", "CVc",
                          sample_name,
                          "_GEX.best")

scRNA.input_path = paste0("~/sc_covidvac/inputs/Meta/subsetted/", 
                          "CVc_scRNA_metadata_", 
                          sample_name, ".csv")

scRNA.output_path = paste0("/mnt/vclab_storage_2025/scOmics/analysis_outputs/RNA/Preprocessing/")

############ Read table ############ 
scRNA.demux_meta <- read.table(scRNA.demux_path, header = T)
scRNA.demux_meta <- select(scRNA.demux_meta, c(BARCODE, DROPLET.TYPE, SNG.BEST.GUESS))

scRNA_meta <- read.csv(scRNA.input_path, header = T, row.names = 1)

#scRNA_meta$Sample_name[scRNA_meta$Sample_name == "Ref_Lonza"] 
scRNA.all_metadata <- merge(scRNA.demux_meta, scRNA_meta, by.x = "SNG.BEST.GUESS", by.y = "Sample_name")
rownames(scRNA.all_metadata) <-  scRNA.all_metadata$BARCODE
scRNA.all_metadata$BARCODE <- NULL

sample.batch_color <- scRNA.all_metadata$Batch_color[1]
```

------------------------------------------------------------------------

## Load Data

```{r}
#| label: load-data
#| eval: false

print("Load input data")
scRNA.data <- Read10X(scRNA.cellranger_path)

print("Load cellbender data")
scRNA.data_cb <- Read10X_h5(scRNA.cellbender_path, use.names = TRUE)

length(colnames(scRNA.data))
length(colnames(scRNA.data_cb))

scRNA.data_cb <- scRNA.data_cb[ ,colnames(scRNA.data)]
length(colnames(scRNA.data_cb))

print("Create Seurat object")
scRNA.obj <- CreateSeuratObject(scRNA.data_cb,
                                project = paste0(sample_name, "_RNA"),
                                min.cells = 0, min.features = 300,
                                meta.data = scRNA.all_metadata)


scRNA.data <- scRNA.data[ ,colnames(scRNA.obj)]
length(colnames(scRNA.data))
# create a new assay to store ADT information
ori_assay <- CreateAssay5Object(counts = scRNA.data)

# add this assay to the previously created Seurat object
scRNA.obj@assays[["ORI"]] <- ori_assay

# Validate that the object now contains multiple assays
Assays(scRNA.obj)
scRNA.obj
```

```{r}
#| eval: false
DefaultAssay(scRNA.obj) <- "RNA"

#Idents(scRNA.obj) <- scRNA.obj$DROPLET.TYPE
#scRNA.obj <- subset(scRNA.obj, idents = c("SNG", "DBL"))
#Idents(scRNA.obj) <- scRNA.obj$orig.ident

scRNA.obj[["percent.mt"]] <- PercentageFeatureSet(scRNA.obj, pattern = "^MT-")
scRNA.obj[["percent.rp"]] <- PercentageFeatureSet(scRNA.obj, pattern = "^RPS|^RPL")
scRNA.obj[["percent.hsp"]]  <- PercentageFeatureSet(scRNA.obj, pattern = "^HSP")
```
